### ISSUE TITLE
implementare UC ricerca per codice o ragione sociale o indirizzo, chiave parziale contenuta

### ISSUE THREAD

**Issue by moretti-matteo** [matteo2025/archivio-clienti-his#6]
implementare UC ricerca per codice o ragione sociale o indirizzo, chiave parziale contenuta

**Comment by capponiFelice92** [comment]
Risolto con commit 23fe4d0d0f226517d61a9d3ae91d8bde41af9ceb

**Comment by moretti-matteo** [comment]
Risolto: f724ad8fbadbcc5a01d1c65858062ea3401672a3
