### ISSUE TITLE
implementare UC seleziona con conferma, modifica e annulla modifica

### ISSUE THREAD

**Issue by moretti-matteo** [matteo2025/archivio-clienti-his#8]
dopo aver risolto ticket implementare UC selezione #7 implementare UC seleziona con conferma, modifica e annulla modifica

**Comment by capponiFelice92** [comment]
risolto con commit ce7287b84aa74289950edb39375531290b1f2ffe

**Comment by moretti-matteo** [comment]
È presente un piccolo bug, quando si conferma la modifica non vengono ripuliti i campi di input.

**Comment by nicoloabatecola** [comment]
Risolto bug 5d5a98b1eaa8d52db394b54ffd0f3b3663343339
